#!/usr/bin/env bash
# 1-debugging_made_short
# configures a server to listening on port 80 of all server's active IPv4 IPs
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid

