#!/usr/bin/env bash
# Write a Bash script that displays To infinity and beyond indefinitely.
#+ a sleep 2 in between each iteration.
flag=0
while [ $flag -eq 0 ]
do
        echo "To infinity and beyond"
	sleep 2
done
