#!/usr/bin/env bash
# List format is used to display numbers from 1 to 100.
# When the number is a multiple of 3 and 5, "FizzBuzz" is printed.
# When the number is a multiple of 3 "Fizz" is printed.
# When the number is a multiple of 5, "Buzz" is printed.
# If so, the number is printed.
for num in {1..100}
do
  if (( num % 3 == 0 && num % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( num % 3 == 0 ))
  then
    echo "Fizz"
  elif (( num % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$num"
  fi
done
