#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`.
# Only the path to the user's home directory, username, and user id is displayed.

while read -r passwd; 
do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
