#!/usr/bin/env bash
# Parses Apache log files in list format.
# Groups visitors by IP and HTTP status code.
# Displays the total instances, IP address, and HTTP status
#+ code for every log, sorted by order.
awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rnvc
